import React from 'react';
import { AgroState, AgroChallan } from '../types';
import { ReportLayout } from './ReportLayout';

export const ChallanReport: React.FC<{ state: AgroState }> = ({ state }) => {
  const columns = [
    { header: 'Challan No', accessor: 'challanNo' as const },
    { header: 'Date', accessor: 'date' as const },
    { header: 'Party Name', accessor: 'partyName' as const },
    { header: 'Items', accessor: (item: AgroChallan) => item.items.map(i => `${i.name} (${i.quantity})`).join(', '), className: 'max-w-[250px] truncate' },
    { header: 'Generated By', accessor: (item: any) => 'System' }
  ];

  return (
    <ReportLayout 
      title="Manual Challan & Movement Report"
      data={state.challans}
      columns={columns}
      exportFileName="challan_report"
    />
  );
};
